// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6IouY7FIniiV0PZTFJLek4KQie231kcs',
    appId: '1:813990054880:web:e8f436eb2fbfc99bc33985',
    messagingSenderId: '813990054880',
    projectId: 'mychatapp-d0126',
    authDomain: 'mychatapp-d0126.firebaseapp.com',
    storageBucket: 'mychatapp-d0126.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnjWIuyClq3TYjaSxiPKszbOwvQRkC0Cg',
    appId: '1:813990054880:android:58ab384ac6f09c20c33985',
    messagingSenderId: '813990054880',
    projectId: 'mychatapp-d0126',
    storageBucket: 'mychatapp-d0126.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSl2cSCUWu0sU6vAHfifjLjyY5vDeaRfk',
    appId: '1:813990054880:ios:aa2d79c318af967fc33985',
    messagingSenderId: '813990054880',
    projectId: 'mychatapp-d0126',
    storageBucket: 'mychatapp-d0126.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSl2cSCUWu0sU6vAHfifjLjyY5vDeaRfk',
    appId: '1:813990054880:ios:853b9ff62ba33e51c33985',
    messagingSenderId: '813990054880',
    projectId: 'mychatapp-d0126',
    storageBucket: 'mychatapp-d0126.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
